config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls
urlpatterns = [
    path('', include('pages.urls',namespace='pages')),
    path('listings/', include('listings.urls',namespace='listings')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +  debug_toolbar_urls()

admin.site.site_header = "Clinic Administration"
admin.site.site_title = "Clinic Admin Portal"
admin.site.index_title = "Welcome to Clinic Portal"

listings/urls.py
from django.urls import path
from . import views

app_name = 'listings'

urlpatterns = [
    path('', views.listings, name='index'),
    path('<int:listing_id>/', views.listing, name='listing'),
    path('search/', views.search, name='search'),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
  path('',views.index, name='index'),
  path('about', views.about, name='about')
]

doctors/models.py
from django.db import models

# Create your models here
class Doctor(models.Model):
    name= models.CharField(max_length=200)
    photo=models.ImageField(upload_to='photos/%Y/%m/%d/')
    description = models.TextField(blank=True)
    phone = models.CharField(max_length=20, blank='00000000')
    email = models.EmailField(max_length=50,unique=True,blank=False)
    is_mvp = models.BooleanField(default=True)
    hire_date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name

listings/models.py
from django.db import models
from doctors.models import Doctor
# Create your models here.
class Listing(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    district = models.CharField(max_length=50)
    description= models.TextField(blank=True)
    services = models.TextField(blank=True)
    service = models.IntegerField()
    room_type = models.CharField(max_length=200, default='')
    rooms= models.CharField(max_length=2)
    professions = models.CharField(max_length=200, default='')
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    is_published = models.BooleanField(default=True)
    list_date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-list_date']
        indexes = [models.Index(fields=['list_date'])]
    def __str__(self):
        return self.title

pages/models.py
from django.db import models

# Create your models here.

doctors/views.py
from django.shortcuts import render

# Create your views here.

listings/views.py
from django.shortcuts import render, get_object_or_404
from .models import Listing
from django.core.paginator import Paginator
# Create your views here.

def listings(request):
    listings = Listing.objects.filter(is_published=True)
    paginator = Paginator(listings,3)
    page = request.GET.get('page')
    paged_listings = paginator.get_page(page)
    context = {"listings" : paged_listings}
    return render(request, 'listings/listings.html', context)

# 從db找id, 無就做404
def listing(request, listing_id):  
    listing = get_object_or_404(Listing, pk=listing_id)
    context = {"listing" : listing}
    return render(request, 'listing/listing.html', context)

def search(request):
    return render(request, 'listings/search.html')

pages/views.py
from django.shortcuts import render
from listings.models import Listing

# Create your views here.
def index(request):
    listings = Listing.objects.all()
    context = {"listings": listings}
    return render(request,'pages/index.html', context)
def about(request):
    print(request, request.path)
    return render(request,'pages/about.html')

templates/adm/base-site.html
{% extends "admin/base.html" %} 
{% load static %}
{% block branding %}
<link rel="stylesheet" href="{% static 'css/admin.css' %}" />
<img
 src="{% static 'img/logo.png' %}"
 alt="Clinic Logo"
 class="brand_img"
 heihgt="35"
 width="45"
/>

<span class="brands"> Clinic Center Admin</span>

{% endblock branding %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href={% static "css/all.css" %} />
    <!-- Bootstrap -->
    <link rel="stylesheet" href={% static "css/bootstrap.css" %} />
    <!-- lightbox -->
    <link rel="stylesheet" href={% static "css/lightbox.min.css" %} />
    <!-- Custom -->
    <link rel="stylesheet" href={% static "css/style.css" %} />
    

    <title>BC Health Care</title>
  </head>
  <body>
    <!-- topbar -->
    {% include 'partials/_topbar.html' %}
    <!-- navbar -->
    {% include 'partials/_navbar.html' %}
    <!-- content -->
    {% block content %}{% endblock %}
    <!-- footer -->
    {% include 'partials/_footer.html' %}
    <script src={% static "js/jquery-3.3.1.min.js"  %}></script>
    <script src={% static "js/bootstrap.bundle.min.js" %}></script>
    <script src={% static "js/lightbox.min.js" %}></script>
    <script src={% static "js/main.js" %}></script>
  </body>
</html>

templates/listings/listing.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="assets/css/all.css" />
    <!-- Bootstrap -->
    <link rel="stylesheet" href="assets/css/bootstrap.css" />
    <!-- Lightbox -->
    <link href="assets/css/lightbox.min.css" rel="stylesheet" />
    <!-- Custom -->
    <link rel="stylesheet" href="assets/css/style.css" />

    <title>BC Health Care</title>
  </head>

  <body>
    <!-- Top Bar -->
    <section id="top-bar" class="p-3">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <i class="fas fa-phone"></i> (852)-555-5555
          </div>
          <div class="col-md-4">
            <i class="fas fa-envelope-open"></i> contact@healthcare.co
          </div>
          <div class="col-md-4">
            <div class="social text-right">
              <a href="#">
                <i class="fab fa-twitter"></i>
              </a>
              <a href="#">
                <i class="fab fa-facebook"></i>
              </a>
              <a href="#">
                <i class="fab fa-linkedin"></i>
              </a>
              <a href="#">
                <i class="fab fa-instagram"></i>
              </a>
              <a href="#">
                <i class="fab fa-pinterest"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
      <div class="container">
        <a class="navbar-brand" href="index.html">
          <img src="assets/img/logo.png" class="logo" alt="" />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNavAltMarkup"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <ul class="navbar-nav">
            <li class="nav-item active mr-3">
              <a class="nav-link" href="index.html">Home</a>
            </li>
            <li class="nav-item mr-3">
              <a class="nav-link" href="about.html">About</a>
            </li>
            <li class="nav-item mr-3">
              <a class="nav-link" href="listings.html"
                >Inpatient medical services</a
              >
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-3">
              <a class="nav-link" href="register.html">
                <i class="fas fa-user-plus"></i> Register</a
              >
            </li>
            <li class="nav-item mr-3">
              <a class="nav-link" href="login.html">
                <i class="fas fa-sign-in-alt"></i>

                Login</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <section id="showcase-inner" class="py-5 text-white">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-12">
            <h1 class="display-4">{{listing.title | title}}</h1>
            <p class="lead"><i class="fas fa-map-marker"></i> {{listing.district | title}}</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
      <div class="container">
        <nav>
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="index.html">Home</a>
            </li>
            <li class="breadcrumb-item">
              <a href="listings.html">Listings</a>
            </li>
            <li class="breadcrumb-item active">Lifeline Wellness Center</li>
          </ol>
        </nav>
      </div>
    </section>

    <!-- Listing -->
    <section id="listing" class="py-4">
      <div class="container">
        <a href="{% url 'listings:index' %}" class="btn btn-light mb-4">Back To Listings</a>
        <div class="row">
          <div class="col-md-9">
            <!-- Home Main Image -->
            <img
              src="assets/img/clinics/clinic-1.jpg"
              alt=""
              class="img-main img-fluid mb-3"
            />
            <!-- Thumbnails -->
            <div class="row mb-5 thumbs">
              <div class="col-md-">
                {% if listing.photo_1 %}
                  <a href="{{listing.photo_1.url}}" data-lightbox="home-images">
                    <img src="{{listing.photos_1.url}}" alt="" class="img-fluid" />
                  </a>
                {% endif %}
              </div>
              <div class="col-md-2">
                {% if listing.photo_2 %}
                  <a href="{{listing.photo_2.url}}" data-lightbox="home-images">
                    <img src="{{listing.photos_1.url}}" alt="" class="img-fluid" />
                  </a>
                {% endif %}
              </div>
              <div class="col-md-2">
                {% if listing.photo_3 %}
                  <a href="{{listing.photo_3.url}}" data-lightbox="home-images">
                    <img src="{{listing.photos_1.url}}" alt="" class="img-fluid" />
                  </a>
                {% endif %}
              </div>
              <div class="col-md-2">
                {% if listing.photo_4 %}
                  <a href="{{listing.photo_4.url}}" data-lightbox="home-images">
                    <img src="{{listing.photos_1.url}}" alt="" class="img-fluid" />
                  </a>
                {% endif %}
              </div>
              <div class="col-md-2">
                <a
                  href="assets/img/clinics/clinic-inside-5.jpg"
                  data-lightbox="home-images"
                >
                  <img
                    src="assets/img/clinics/clinic-inside-5.jpg"
                    alt=""
                    class="img-fluid"
                  />
                </a>
              </div>
              <div class="col-md-2">
                <a
                  href="assets/img/clinics/clinic-inside-6.jpg"
                  data-lightbox="home-images"
                >
                  <img
                    src="assets/img/clinics/clinic-inside-6.jpg"
                    alt=""
                    class="img-fluid"
                  />
                </a>
              </div>
            </div>
            <!-- Fields -->
            <div class="row mb-5 fields">
              <div class="col-md-6">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item text-secondary">
                    <i class="fas fa-money-bill-alt"></i> {{listing.title}} Inpatient Fee
                    Estimate:
                    <span class="float-right">$20,000/Day</span>
                  </li>
                  <li class="list-group-item text-secondary">
                    <i class="fas fa-bed"></i> Bedrooms:
                    <span class="float-right">{{listing.rooms}}</span>
                  </li>
                  <li class="list-group-item text-secondary">
                    <i class="fas fa-bath"></i> Bathrooms:
                    <span class="float-right">{{listing.room_type}}</span>
                  </li>
                  <li class="list-group-item text-secondary">
                    <i class="fas fa-dumbbell"></i> Treatment:
                    <span class="float-right"> Have </span>
                  </li>
                </ul>
              </div>
              <div class="col-md-6">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item text-secondary">
                    <i class="fas fa-th-large"></i> Restrooms:
                    <span class="float-right">Have</span>
                  </li>
                  <li class="list-group-item text-secondary">
                    <i class="fas fa-square"></i> Specialized Care:
                    <span class="float-right">No</span>
                  </li>
                  <li class="list-group-item text-secondary">
                    <i class="fas fa-calendar"></i> Preventative Services:
                    <span class="float-right">Have</span>
                  </li>
                  <li class="list-group-item text-secondary">
                    <i class="fas fa-bed"></i> Minor Surgical Procedures:
                    <span class="float-right">No</span>
                  </li>
                </ul>
              </div>
            </div>

            <!-- Description -->
            <div class="row mb-5">
              <div class="col-md-12">
                {{listing.description}}
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <div class="card mb-3">
              <img
                class="card-img-top"
                src={{listing.doctor.photo.url}}
                alt="Seller of the month"
              />
              <div class="card-body">
                <h5 class="card-title">Medical Practitioner</h5>
                <h6 class="text-secondary">{{listing.doctor.name}}</h6>
              </div>
            </div>
            <button
              class="btn-primary btn-block btn-lg"
              data-toggle="modal"
              data-target="#inquiryModal"
            >
              Make An Inquiry
            </button>
          </div>
        </div>
      </div>
    </section>

    <!-- Inquiry Modal -->
    <div class="modal fade" id="inquiryModal" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
            <button type="button" class="close" data-dismiss="modal">
              <span>&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form>
              <div class="form-group">
                <label for="property_name" class="col-form-label"
                  >Property:</label
                >
                <input
                  type="text"
                  name="listing"
                  class="form-control"
                  value="45 Prince Street"
                  disabled
                />
              </div>
              <div class="form-group">
                <label for="name" class="col-form-label">Name:</label>
                <input type="text" name="name" class="form-control" required />
              </div>
              <div class="form-group">
                <label for="email" class="col-form-label">Email:</label>
                <input
                  type="email"
                  name="email"
                  class="form-control"
                  required
                />
              </div>
              <div class="form-group">
                <label for="phone" class="col-form-label">Phone:</label>
                <input type="text" name="phone" class="form-control" />
              </div>
              <div class="form-group">
                <label for="message" class="col-form-label">Message:</label>
                <textarea name="message" class="form-control"></textarea>
              </div>
              <hr />
              <input
                type="submit"
                value="Send"
                class="btn btn-block btn-secondary"
              />
            </form>
          </div>
        </div>
      </div>
    </div>

    <!-- Footer -->
    <footer id="main-footer" class="py-4 bg-primary text-white text-center">
      Copyright &copy;
      <span class="year"></span> BC Health Care
    </footer>

    <script src="assets/js/jquery-3.3.1.min.js "></script>
    <script src="assets/js/bootstrap.bundle.min.js "></script>
    <script src="assets/js/lightbox.min.js"></script>
    <script src="assets/js/main.js "></script>
  </body>
</html>

templates/listings/listings.html
{% extends "base.html" %}
<!--load base-->
{% load static %}
<!--load static -->
{% load humanize %}
<!-- humanize -->
{% block content %}
<section id="showcase-inner" class="py-5 text-white">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-4">Browse Our Clinic</h1>
        <p class="lead">
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt,
          pariatur!
        </p>
      </div>
    </div>
  </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'pages:index' %}">
            <i class="fas fa-home"></i> Home</a
          >
        </li>
        <li class="breadcrumb-item active">Browse Listings</li>
      </ol>
    </nav>
  </div>
</section>

<!-- Listings -->
<section id="listings" class="py-4">
  <div class="container">
    <div class="row">
      {% if listings %}
      <!-- Listing 1 -->
      {% for listing in listings %}
      <div class="col-md-6 col-lg-4 mb-4">
        <div class="card listing-preview">
          <img class="card-img-top" src="{{ listing.photo_main.url }}" alt="" />
          <div class="card-img-overlay"></div>
          <div class="card-body">
            <div class="listing-heading text-center">
              <h4 class="text-primary">{{ listing.title | title }}</h4>
              <p>
                <i class="fas fa-map-marker text-secondary"></i>
                {{listing.district | title}}
              </p>
            </div>
            <hr />
            <div class="row py-2 text-secondary">
              <div class="col-6">
                <i class="fas fa-th-large"></i>
                Services {{listing.service|apnumber | capfirst}}
              </div>
              <div class="col-6"><i class="fas fa-dumbbell"></i> Treatment</div>
            </div>
            <div class="row py-2 text-secondary">
              <div class="col-6">
                <i class="fas fa-bed"></i> rooms {{listing.rooms}}
              </div>
              <div class="col-6"><i class="fas fa-bath"></i> Bathrooms</div>
            </div>
            <hr />
            <div class="row py-2 text-secondary">
              <div class="col-12">
                <i class="fas fa-user"></i> {{listing.doctor.name}}
              </div>
            </div>
            <div class="row text-secondary pb-2">
              <div class="col-12">
                <i class="fas fa-clock"></i> {{listing.list_date | timesince}}
              </div>
            </div>
            <hr />
            {% comment %} listing {% endcomment %}
            <a
              {% comment %} listings\urls.py => listings  {% endcomment %}
              href="{% url 'listings:listing' listing.id %}"  
              class="btn btn-primary btn-block"
              >More Info</a
            >
          </div>
        </div>
      </div>
      {% endfor %} {% else %}
      <div class="col-md-12">
        <h2>No Clinic Available</h2>
      </div>
      {% endif %}
    </div>
    <div class="row">
      <div class="col-md-12">
        {% if listings.has_other_pages %}
        <ul class="pagination">
          {% if listings.has_previous %}
          <li class="page-item">
            <a
              class="page-link"
              href="?page={{ listings.previous_page_number }}"
              >&laquo;</a
            >
          </li>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#">&laquo;</a>
          </li>
          {% endif %}
          <!--for loop page number-->
          {% for i in listings.paginator.page_range %}
          <!--page number-->
          {% if listings.number == i %}
          <li class="page-item active">
            <a class="page-link">{{ i }}</a>
          </li>
          {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
          {% endif %} {% endfor %}
          <li class="page-item">
            <a class="page-link" href="#">2</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">3</a>
          </li>
          {% if listings.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ listings.next_page_number }}"
              >&raquo;</a
            >
          </li>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#">&raquo;</a>
          </li>
          {% endif %}
        </ul>
        {% endif %}
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/listings/search.html
<h1>Search</h1>

templates/pages/about.html
{% extends 'base.html' %}
{% load static %}
<!-- about main content-->
{% block content %}
<section id="showcase-inner" class="py-5 text-white">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-4">About BC Health Care</h1>
        <p class="lead">
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt,
          pariatur!
        </p>
      </div>
    </div>
  </div>
</section>

<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href={% url 'pages:index' %}> <i class="fas fa-home"></i> Home</a>
        </li>
        <li class="breadcrumb-item active">About</li>
      </ol>
    </nav>
  </div>
</section>

<section id="about" class="py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <h2>
          We Search For The Your health, your home – we help you find the right
          clinic.
        </h2>
        <p class="lead">
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt,
          pariatur!
        </p>

        <img src={% static 'img/about.jpg' %} alt="" />
        <p class="mt-4">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis
          esse officia repudiandae ad saepe ex, amet neque quod accusamus rem
          quia magnam magni dolorum facilis ullam minima perferendis?
          Exercitationem at quaerat commodi id libero eveniet harum perferendis
          laborum molestias quia.
        </p>
      </div>
      <div class="col-md-4">
        <div class="card">
          {% comment %} img {% endcomment %}
          <img
            class="card-img-top"
            src="assets/img/doctors/kyle.jpg"
            alt="Seller of the month"
          />
          <div class="card-body">
            <h5 class="card-title">Top Doctor</h5>
            <h6 class="text-secondary">Kyle chan</h6>
            <p class="card-text">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis
              nesciunt amet, illo itaque similique repellat. content.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="work" class="bg-dark text-white text-center">
  <h2 class="display-4">We Work For You</h2>
  <h4>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem velit
    aperiam, unde aliquid at similique!
  </h4>
  <hr />
  {% comment %} listings {% endcomment %}
  <a href="listings.html" class="btn btn-secondary text-white btn-lg"
    >View Our Featured Listings</a
  >
</section>

<!-- Team -->
<section id="team" class="py-5">
  <div class="container">
    <h2 class="text-center pb-4">Our Team</h2>
    <div class="row text-center">
      <div class="col-md-4">
        {% comment %} img {% endcomment %}
        <img
          src="assets/img/doctors/kyle.jpg"
          alt=""
          class="rounded-circle mb-3 img-fluid"
          style="object-fit: cover; width: 300px; height: 300px"
        />
        <h4>Kyle Chan</h4>
        <p class="text-success">
          <i class="fas fa-award text-success"></i> Doctor
        </p>
        <hr />
        <p><i class="fas fa-phone"></i> (852)-555-5555</p>
        <p><i class="fas fa-envelope-open"></i> kyle@healthcare.co</p>
      </div>

      <div class="col-md-4">
        {% comment %} img {% endcomment %}
        <img
          src="assets/img/doctors/emma.jpg"
          alt=""
          class="rounded-circle mb-3 img-fluid"
          style="object-fit: cover; width: 300px; height: 300px"
        />
        <h4>Emma Lee</h4>
        <p class="text-success">Doctor</p>
        <hr />
        <p><i class="fas fa-phone"></i> (852)-444-4444</p>
        <p><i class="fas fa-envelope-open"></i> emma@healthcare.co</p>
      </div>

      <div class="col-md-4">
        {% comment %} img {% endcomment %}
        <img
          src="assets/img/doctors/jenny.jpg"
          alt=""
          class="rounded-circle mb-3 img-fluid"
          style="object-fit: cover; width: 300px; height: 300px"
        />
        <h4>Jenny Cheung</h4>
        <p class="text-success">Doctor</p>
        <hr />
        <p><i class="fas fa-phone"></i> (852)-333-3333</p>
        <p><i class="fas fa-envelope-open"></i> jenny@healthcare.co</p>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/partials/_footer.html
<footer id="main-footer" class="py-4 bg-primary text-white text-center">
  Copyright &copy;
  <span class="year"></span> BC Health Care
</footer>

templates/partials/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
  <div class="container">
    <a class="navbar-brand" href={% url 'pages:index' %}>
      <img src={% static "img/logo.png" %} class="logo" alt="" />
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarNavAltMarkup"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav">
        <li {% if '/' == request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
          <a class="nav-link" href={% url 'pages:index' %}>Home</a>
        </li>
        <li {% if '/about' == request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
          <a class="nav-link" href={% url 'pages:about' %}>About</a>
        </li>
        <li {% if '/listings/' == request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
          <a class="nav-link" href={% url 'listings:index' %}>
            Inpatient medical services
          </a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item mr-3">
          {% comment %} fix register {% endcomment %}
          <a class="nav-link" href="register.html">
            <i class="fas fa-user-plus"></i> Register</a
          >
        </li>
        <li class="nav-item mr-3">
          {% comment %} fix login {% endcomment %}
          <a class="nav-link" href="login.html">
            <i class="fas fa-sign-in-alt"></i>

            Login</a
          >
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/partials/_topbar.html
<section id="top-bar" class="p-3">
  <div class="container">
    <div class="row">
      <div class="col-md-4"><i class="fas fa-phone"></i> (852)-555-5555</div>
      <div class="col-md-4">
        <i class="fas fa-envelope-open"></i> contact@healthcare.co
      </div>
      <div class="col-md-4">
        <div class="social text-right">
          <a href="#">
            <i class="fab fa-twitter"></i>
          </a>
          <a href="#">
            <i class="fab fa-facebook"></i>
          </a>
          <a href="#">
            <i class="fab fa-linkedin"></i>
          </a>
          <a href="#">
            <i class="fab fa-instagram"></i>
          </a>
          <a href="#">
            <i class="fab fa-pinterest"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>